name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check python3 version
        run: |
          make check
      - name: Test sync file and Remove
        run: |
          make sync
          make remove
